---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: science
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  selector:
    matchLabels:
      type: "usb-drive"
      disk: "d"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: science
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: science
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:16'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: science
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - name: postgres-tcp
      port: 5432           # port exposed by ingress
      targetPort: 5432     # port exposed by the pod
      protocol: TCP
  externalTrafficPolicy: Local

