
# ~/mc cp oscar/models/mistral-7b-openorca.Q6_K.gguf mistral-7b-openorca.Q6_K.gguf

@llm_endpoint=http://192.168.1.27

###
POST {{llm_endpoint}}/v1/embeddings 
Content-Type: application/json

{"input": "Test", "model": "text-embedding-ada-002"}

###
#  "model": "mixtral-instruct",
POST {{llm_endpoint}}/v1/chat/completions
Content-Type: application/json

{
    "model": "mistral-7b-openorca.Q6_K.gguf",
    "messages": [
        {"role": "system", "content": "Output only valid JSON"},
        {"role": "system", "content": "Do stuff" },
        {"role": "user", "content": "how do I make cake?" }
    ],
    "temperature": 0.7
}

###
GET {{llm_endpoint}}/v1/models
Content-Type: application/json


# @software{lian2023mistralorca1
#   title = {MistralOrca: Mistral-7B Model Instruct-tuned on Filtered OpenOrcaV1 GPT-4 Dataset},
#   author = {Wing Lian and Bleys Goodson and Guan Wang and Eugene Pentland and Austin Cook and Chanvichet Vong and "Teknium"},
#   year = {2023},
#   publisher = {HuggingFace},
#   journal = {HuggingFace repository},
#   howpublished = {\url{https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca},
# }
# @misc{mukherjee2023orca,
#       title={Orca: Progressive Learning from Complex Explanation Traces of GPT-4},
#       author={Subhabrata Mukherjee and Arindam Mitra and Ganesh Jawahar and Sahaj Agarwal and Hamid Palangi and Ahmed Awadallah},
#       year={2023},
#       eprint={2306.02707},
#       archivePrefix={arXiv},
#       primaryClass={cs.CL}
# }
# @misc{longpre2023flan,
#       title={The Flan Collection: Designing Data and Methods for Effective Instruction Tuning},
#       author={Shayne Longpre and Le Hou and Tu Vu and Albert Webson and Hyung Won Chung and Yi Tay and Denny Zhou and Quoc V. Le and Barret Zoph and Jason Wei and Adam Roberts},
#       year={2023},
#       eprint={2301.13688},
#       archivePrefix={arXiv},
#       primaryClass={cs.AI}
# }
