apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-pv-200-volume
  labels:
    type: usb-drive
    disk: "d"
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usbd/200"
  # The usb drive is plugged into the master node 
  # in my setup
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kworker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-pv-100-volume
  labels:
    type: usb-drive
    disk: "d"
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  capacity:
    storage: 80Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usbd/100"
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kworker2

---
##
## My Jellyfin disk of media. This should only be mounted on the control node
## and should not be deleted when the pod is deleted.
##
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-jelly-1-pv-volume
  labels:
    type: usb-drive
    disk: "c"
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usbc/config"
  # The usb drive is plugged into the master node 
  # in my setup
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kmaster

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-jelly-2-pv-volume
  labels:
    type: usb-drive
    disk: "c"
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usbc/cache"
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kmaster

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-jelly-3-pv-volume
  labels:
    type: usb-drive
    disk: "c"
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  capacity:
    storage: 414Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usbc/media"
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kmaster