###
### WARNING: this is very specific to Ubuntu, and Ubuntu version!
###

# NVIDIA_GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g')
# KUBELET_OPTS="$KUBELET_OPTS --node-labels='alpha.kubernetes.io/nvidia-gpu-name=$NVIDIA_GPU_NAME,alpha.kubernetes.io/nvidia-gpu=1'"
# echo "KUBELET_OPTS=$KUBELET_OPTS" > /etc/default/kubelet
# systemctl restart kubelet.service
# 
# source /etc/default/kubelet

---
- name: add the cuda deb package
  become: true
  ansible.builtin.shell: |
    curl -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    dpkg -i cuda-keyring_1.1-1_all.deb

- name: install cuda binary
  become: true
  ansible.builtin.apt:
    pkg:
      - cuda=12.3.2-1
      - nvidia-gds=12.3.2-1
    state: present
    update_cache: true

...
