---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: job-example
spec:
  #          ┌───────────── minute (0 - 59)
  #          │ ┌───────────── hour (0 - 23)
  #          │ │ ┌───────────── day of the month (1 - 31)
  #          │ │ │ ┌───────────── month (1 - 12)
  #          │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
  #          │ │ │ │ │
  #          │ │ │ │ │
  #          │ │ │ │ │
  #          * * * * *
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: readonly-sa
          containers:
            - name: job-example
              image: my-repo/my-container:52f50c7
              env:
                - name: SOME_ENV_VAR
                  value: "my-env-value"
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 500m
                  ephemeral-storage: 5Gi
                  memory: 2Gi
          restartPolicy: Never
  concurrencyPolicy: Forbid
