apiVersion: v1
kind: PersistentVolume
metadata:
  name: usb-pv-volume
  labels:
    type: local
spec:
  # This will keep the data on the disk after the pod is shutdown
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 293Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/usbd"
