---

- name: add the container.io repositories
  become: true
  ansible.builtin.shell: |
    cat /etc/apt/sources.list.d/docker.list && echo "AlreadyDoneDocker" || \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker-archive-keyring.gpg; \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
  register: cmd_resultd
  changed_when: cmd_resultd.stdout != "AlreadyDoneDocker"

- name: update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: install containerd.io
  become: true
  ansible.builtin.apt:
    pkg:
      - containerd.io
    state: present
    update_cache: true

...
