---
- name: add the k8 repositories
  become: true
  ansible.builtin.shell: |
    cat /etc/apt/sources.list.d/kubernetes.list && echo "K8Added" || \
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg; \
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8_version }}/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list;
  register: cmd_result
  changed_when: cmd_result.stdout != "K8Added"

- name: update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

# now install these on workers and master
- name: install kubeadm and friends
  become: true
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
    state: present
    update_cache: true

####################################################################
## Ubuntu Fixes

- name: kill swap and update hosts
  become: true
  ansible.builtin.shell: |
    cat fixes_applied.txt && echo "FixesApplied" || \
    swapoff -a && sed -i '/swap/d' /etc/fstab; \
    echo "# skoupidia boxes" >> /etc/hosts; \
    echo "192.168.1.15 kmaster" >> /etc/hosts; \
    echo "192.168.1.13 kworker1" >> /etc/hosts; \
    echo "192.168.1.14 kworker2" >> /etc/hosts; \
    touch fixes_applied.txt
  register: cmd_result_swp
  changed_when: cmd_result_swp.stdout != "FixedApplied"

- name: enable kernel mods
  become: true
  ansible.builtin.shell: |
    cat /etc/modules-load.d/k8s.conf && echo "FixesApplied" || \
    modprobe overlay; \
    modprobe br_netfilter; \
    cat >/etc/modules-load.d/k8s.conf <<EOF
    overlay
    br_netfilter
    EOF
  register: cmd_result_mod
  changed_when: cmd_result_mod.stdout != "FixedApplied"

- name: enable bridge
  become: true
  ansible.builtin.shell: |
    cat /etc/sysctl.d/kubernetes.conf && echo "FixesApplied" || \
    cat >/etc/sysctl.d/kubernetes.conf <<EOF
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    EOF
  register: cmd_result_bg
  changed_when: cmd_result_bg.stdout != "FixedApplied"

- name: enable bridge
  become: true
  ansible.builtin.shell: |
    sysctl --system

...
